name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        working-directory: ./bun-api
        run: docker build . --file Dockerfile --tag bun-api:$(date +%s)